# Generated by Django 5.2.6 on 2025-09-28 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.IntegerField()),
                ('validitytime', models.IntegerField()),
                ('endtime', models.IntegerField()),
                ('creator', models.CharField(max_length=50)),
                ('qr', models.ImageField(upload_to='qr_codes/')),
                ('data', models.TextField()),
            ],
        ),
    ]
