# Generated by Django 5.2.7 on 2025-10-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
